line-length = 120

[lint]
select = [
    "F",       # Pyflakes 
    "E",       # pycodestyle (Error)
    "W",       # pycodestyle (Warning)
    "N",       # pep8-naming
    "RET",     # flake8-return
    "S307",    # suspicious-eval-usage
    "SLF",     # flake8-self
    "BLE",     # flake8-blind-except

    # TODO: 
    # "D",     # pydocstyle
    # "NPY"    # NumPy-specific rules
]

ignore = [
    "E402",    # module-import-not-at-top-of-file
    "E731",    # lambda-assignment
    "F403",    # undefined-local-with-import-star
    "F405",    # undefined-local-with-import-star-usage
    "RET504",  # unnecessary-assign
    "NPY002"   # numpy-legacy-random
]

[lint.per-file-ignores] 
"__init__.py" = ["F401"]        # unused-import
"utils_notebook.py" = ["F401"]  # unused-import
